image: maven:3.6.3-jdk-11

variables:
  GROUP_ID: kueres
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - deploy

maven-build:
  stage: build
  tags:
    - ILT
  script: 'mvn package -Dmaven.test.skip=true -B -s ci_settings.xml'
  artifacts:
    paths:
      - ./target/$ARTIFACT_ID-$VERSION.jar

deploy-maven:
  stage: deploy
  tags:
    - ILT
  only:
    - master
  script:
    - 'apt update'
    - 'apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common'
    - 'curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -'
    - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"'
    - 'apt update'
    - 'apt-cache policy docker-ce'
    - 'apt install -y docker-ce'
    - 'curl -L https://github.com/docker/compose/releases/download/1.28.4/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose'
    - 'chmod +x /usr/local/bin/docker-compose'
    - 'mvn deploy -B -s ci_settings.xml'