image: maven:3.6.3-jdk-11

variables:
  GROUP_ID: kueres
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - deploy

maven-build:
  stage: build
  tags:
    - ILT
  script: "mvn verify -B -s ci_settings.xml"
  artifacts:
    paths:
      - target/*.jar

deploy-maven:
  stage: deploy
  tags:
    - ILT
  only:
    - master
  script: 
    - |
      mvn deploy:deploy-file -s ci_settings.xml
      -DgroupId=$GROUP_ID
      -DartifactId=$ARTIFACT_ID
      -Dversion=$VERSION
      -Dpackaging=jar
      -Dfile=/target/${ARTIFACT_ID}-${VERSION}.jar
      -DrepositoryId=gitlab-maven
      -Durl=https://gitlab-ext.iosb.fraunhofer.de/api/v4/projects/2562/packages/maven