image: maven:3.6.3-jdk-11

stages:
  - test
  - deploy

test-maven:
  stage: test
  tags:
    - ILT
  script:
    - "mvn verify"

deploy-maven:
  stage: deploy
  tags:
    - ILT
  only:
    - master
  script:
    - 'mvn deploy -s ci_settings.xml'
