image: maven:3.6.3-jdk-11

variables:
  GROUP_ID: kueres
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - deploy

maven-build:
  stage: build
  tags:
    - ILT
  script: mvn package -Dmaven.test.skip=true -B -s ci_settings.xml
  artifacts:
    paths:
      - ./target/$ARTIFACT_ID-$VERSION.jar

deploy-maven:
  stage: deploy
  tags:
    - ILT
  only:
    - master
  script:
    - apk add docker-compose
    - 'mvn deploy -B -s ci_settings.xml'