image: gitlab-ext.iosb.fraunhofer.de:4567/ilt-pse/ws20_21-mobile-anwendung-zur-unterst-tzung-im-kulturg-terschutz/kueres-backend/maven-docker-compose-cli:openjdk-11

variables:
  GROUP_ID: kueres
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - deploy

maven-build:
  stage: build
  tags:
    - ILT
  script: 'mvn package -Dmaven.test.skip=true -B -s ci_settings.xml'
  artifacts:
    paths:
      - ./target/$ARTIFACT_ID-$VERSION.jar

deploy-maven:
  stage: deploy
  tags:
    - ILT
  only:
    - master
  script:
    - 'mvn deploy -B -s ci_settings.xml'
